environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files\Java\jdk9
  - JAVA_HOME: C:\Program Files\Java\jdk10

install:
  - choco install gradle
  - gradle --version

build_script:
  - gradle assemble

test_script:
  - gradle check

cache:
  - C:\Users\appveyor\.gradle
